// Code generated by MockGen. DO NOT EDIT.
// Source: netfilter.go

// Package network is a generated GoMock package.
package network

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockNetfilter is a mock of Netfilter interface
type MockNetfilter struct {
	ctrl     *gomock.Controller
	recorder *MockNetfilterMockRecorder
}

// MockNetfilterMockRecorder is the mock recorder for MockNetfilter
type MockNetfilterMockRecorder struct {
	mock *MockNetfilter
}

// NewMockNetfilter creates a new mock instance
func NewMockNetfilter(ctrl *gomock.Controller) *MockNetfilter {
	mock := &MockNetfilter{ctrl: ctrl}
	mock.recorder = &MockNetfilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNetfilter) EXPECT() *MockNetfilterMockRecorder {
	return m.recorder
}

// AddTable mocks base method
func (m *MockNetfilter) AddTable(table string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTable", table)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTable indicates an expected call of AddTable
func (mr *MockNetfilterMockRecorder) AddTable(table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTable", reflect.TypeOf((*MockNetfilter)(nil).AddTable), table)
}

// DeleteTable mocks base method
func (m *MockNetfilter) DeleteTable(table string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTable", table)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTable indicates an expected call of DeleteTable
func (mr *MockNetfilterMockRecorder) DeleteTable(table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTable", reflect.TypeOf((*MockNetfilter)(nil).DeleteTable), table)
}

// AddChain mocks base method
func (m *MockNetfilter) AddChain(table, chain string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChain", table, chain)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChain indicates an expected call of AddChain
func (mr *MockNetfilterMockRecorder) AddChain(table, chain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChain", reflect.TypeOf((*MockNetfilter)(nil).AddChain), table, chain)
}

// DeleteChain mocks base method
func (m *MockNetfilter) DeleteChain(table, chain string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChain", table, chain)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChain indicates an expected call of DeleteChain
func (mr *MockNetfilterMockRecorder) DeleteChain(table, chain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChain", reflect.TypeOf((*MockNetfilter)(nil).DeleteChain), table, chain)
}

// AddRule mocks base method
func (m *MockNetfilter) AddRule(table, chain, rule string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRule", table, chain, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRule indicates an expected call of AddRule
func (mr *MockNetfilterMockRecorder) AddRule(table, chain, rule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRule", reflect.TypeOf((*MockNetfilter)(nil).AddRule), table, chain, rule)
}
