// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jakub-dzon/k4e-device-worker/internal/metrics (interfaces: DeviceConfigurationProvider)

// Package metrics is a generated GoMock package.
package metrics

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/jakub-dzon/k4e-operator/models"
)

// MockDeviceConfigurationProvider is a mock of DeviceConfigurationProvider interface.
type MockDeviceConfigurationProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceConfigurationProviderMockRecorder
}

// MockDeviceConfigurationProviderMockRecorder is the mock recorder for MockDeviceConfigurationProvider.
type MockDeviceConfigurationProviderMockRecorder struct {
	mock *MockDeviceConfigurationProvider
}

// NewMockDeviceConfigurationProvider creates a new mock instance.
func NewMockDeviceConfigurationProvider(ctrl *gomock.Controller) *MockDeviceConfigurationProvider {
	mock := &MockDeviceConfigurationProvider{ctrl: ctrl}
	mock.recorder = &MockDeviceConfigurationProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceConfigurationProvider) EXPECT() *MockDeviceConfigurationProviderMockRecorder {
	return m.recorder
}

// GetDeviceConfiguration mocks base method.
func (m *MockDeviceConfigurationProvider) GetDeviceConfiguration() models.DeviceConfiguration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceConfiguration")
	ret0, _ := ret[0].(models.DeviceConfiguration)
	return ret0
}

// GetDeviceConfiguration indicates an expected call of GetDeviceConfiguration.
func (mr *MockDeviceConfigurationProviderMockRecorder) GetDeviceConfiguration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceConfiguration", reflect.TypeOf((*MockDeviceConfigurationProvider)(nil).GetDeviceConfiguration))
}
